dist: trusty
language: node_js
node_js:
  - 6

addons:
  apt:
    packages:
      - pulseaudio

env:
  global:
    - DISPLAY=:99.0
  matrix:
    - BROWSER=chrome  BVER=stable
    - BROWSER=chrome  BVER=beta
    - BROWSER=chrome  BVER=unstable
    - BROWSER=firefox BVER=stable

matrix:
  fast_finish: true

  allow_failures:
    - env: BROWSER=chrome  BVER=unstable

before_install:
  - npm install -g npm@'>=3.0.0'

before_script:
  - npm install
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/cucumber_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1600x1200x16
  - pulseaudio --start

script:
  - grunt --verbose

notifications:
  email:
    recipients:
      forward-webrtc-github@webrtc.org
    on_success: change
    on_failure: always
